### ISSUE TITLE
Meta-handbook basic setup

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/our-meta-handbook#8]
- [ ] GitHub
  - [ ] Labels (to match [template labels](https://github.com/very-good-science/our-handbook-template/labels)) 
  - [ ] Issues + [milestone checklist](https://github.com/very-good-science/our-meta-handbook/issues/2) linking
  - [ ] GH Actions (deploying book)
- [ ] Jupyter book
  - [ ] Basic setup
